### ISSUE TITLE
您的程序直接运行会存在一些问题，望可以进行相应修改

### ISSUE THREAD

**Issue by Maninnlack** [chenhaoxing/M2L#3]
拉取您的项目后，直接运行 ` python experiments/run_trainer.py  --cfg ./configs/miniImagenet/MML_N5K1_R12.yaml --device 0`命令会出现以下错误：

1. 需要pyyaml模块，但是在README文件中没有提及，如果没有安装会报`ModuleNotFoundError: No module named 'yaml'`

2.   模块引用存在错误，例如：
```
File "D:\program\shanliang\M2L-main\modules\encoder\__init__.py", line 4, in <module>
    from modules.encoder.wrn28 import *
ModuleNotFoundError: No module named 'modules.encoder.wrn28'
```
还有
```
File "D:\program\shanliang\M2L-main\modules\query\mml.py", line 7, in <module>
    from modules.utils import GraphFunc, _l2norm, l2distance, batched_index_select, print_network
ImportError: cannot import name 'print_network'
```

3. 存在小的细节错误，例如：
```
  File "D:\program\shanliang\M2L-main\dataloader\pretrain_datasets.py", line 24
    if data_folder == "CIFAR-100" or data_folder == "CIFAR-FS"::
SyntaxError: invalid syntax
```

4. 文件模块路径引用存在问题：
```
(pytorch) D:\program\shanliang\M2L-main> python experiments/run_trainer.py  --cfg ./configs/miniImagenet/MML_N5K1_R12.yaml --device 0
Traceback (most recent call last):
  File "experiments/run_trainer.py", line 65, in <module>
    main()
  File "experiments/run_trainer.py", line 43, in main
    os.mkdir(d)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './checkpoint\\miniImagenet_MML_N5K1_R12'
```
我不知道这里是因为什么导致的os.mkdir报错，所以也不敢自己添加文件夹

**Comment by chenhaoxing** [comment]
你好呀，问题4按那个格式创建同名文件夹就行。

**Comment by chenhaoxing** [comment]
前面的问题确实没有细查，抱歉呀，你可以看看ssformers的代码。
